In [1]:
import numpy as np
import matplotlib.pyplot as plt
import tensorflow as tf

In [2]:
tf.constant([[4]])

<tf.Tensor: shape=(1, 1), dtype=int32, numpy=array([[4]])>

In [3]:
tf.random.uniform(shape=(2,3,4))

<tf.Tensor: shape=(2, 3, 4), dtype=float32, numpy=
array([[[0.05821288, 0.28479242, 0.56624174, 0.47173297],
        [0.6653948 , 0.91306627, 0.02118552, 0.08123147],
        [0.9887221 , 0.6308906 , 0.91725695, 0.7480873 ]],

       [[0.4498633 , 0.96697557, 0.10484445, 0.00885344],
        [0.74551976, 0.4732169 , 0.56361055, 0.4638921 ],
        [0.38547254, 0.68476963, 0.485471  , 0.47968125]]], dtype=float32)>

In [4]:
tf.fill([2, 3, 4], 3)

<tf.Tensor: shape=(2, 3, 4), dtype=int32, numpy=
array([[[3, 3, 3, 3],
        [3, 3, 3, 3],
        [3, 3, 3, 3]],

       [[3, 3, 3, 3],
        [3, 3, 3, 3],
        [3, 3, 3, 3]]])>

In [5]:
tf.zeros([2, 3, 4])

<tf.Tensor: shape=(2, 3, 4), dtype=float32, numpy=
array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]], dtype=float32)>

In [6]:
tf.ones([2, 3, 4])

<tf.Tensor: shape=(2, 3, 4), dtype=float32, numpy=
array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]], dtype=float32)>

In [7]:
tensor = tf.ones([2, 3, 4])

In [8]:
tensor

<tf.Tensor: shape=(2, 3, 4), dtype=float32, numpy=
array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]], dtype=float32)>

In [9]:
tensor.ndim

3

In [10]:
a = tf.constant([[1, 2], 
                 [3, 4]])
b = tf.constant([[5, 6], 
                 [7, 8]])
a + b

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 6,  8],
       [10, 12]])>

In [11]:
tf.add(a, b)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 6,  8],
       [10, 12]])>

In [12]:
tf.multiply(a, b)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 5, 12],
       [21, 32]])>

In [13]:
a * b 

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 5, 12],
       [21, 32]])>

In [14]:
tf.matmul(a, b)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[19, 22],
       [43, 50]])>

In [15]:
a @ b

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[19, 22],
       [43, 50]])>

In [16]:
tf.subtract(a, b)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[-4, -4],
       [-4, -4]])>

In [17]:
a - b

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[-4, -4],
       [-4, -4]])>

In [18]:
def f(x):
    return 1 / x ** 2

x = tf.Variable(2.0)
with tf.GradientTape() as tape:
    tape.watch(x)
    y = f(x)
    dydx = tape.gradient(y, x)
    print(dydx)

tf.Tensor(-0.25, shape=(), dtype=float32)
